/* Generated By:JJTree: Do not edit this line. ASTOXPathKleeneStarPath.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.ox.cs.diadem.oxpath.parse.ast;

import uk.ac.ox.cs.diadem.oxpath.parse.OXPathParser;
import uk.ac.ox.cs.diadem.oxpath.parse.ast.custom.ASTOXPathKleeneStarPathCustom;

public class ASTOXPathKleeneStarPath extends ASTOXPathKleeneStarPathCustom {
  public ASTOXPathKleeneStarPath(final int id) {
    super(id);
  }

  public ASTOXPathKleeneStarPath(final OXPathParser p, final int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  @Override
  public Object jjtAccept(final OXPathParserVisitor visitor, final Object data)
      throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b44f22a5db5965828d483b75c70ffd57 (do not edit this line) */
