/* Generated By:JJTree: Do not edit this line. ASTOXPathExtractionMarker.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.ox.cs.diadem.oxpath.parse.ast;

import uk.ac.ox.cs.diadem.oxpath.parse.OXPathParser;
import uk.ac.ox.cs.diadem.oxpath.parse.ast.custom.ASTOXPathExtractionMarkerCustom;

public class ASTOXPathExtractionMarker extends ASTOXPathExtractionMarkerCustom {
  public ASTOXPathExtractionMarker(final int id) {
    super(id);
  }

  public ASTOXPathExtractionMarker(final OXPathParser p, final int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  @Override
  public Object jjtAccept(final OXPathParserVisitor visitor, final Object data)
      throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=57cdad60be715a86222015efb28d3684 (do not edit this line) */
