/* Generated By:JJTree: Do not edit this line. ASTOXPathActionPath.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.ox.cs.diadem.oxpath.parse.ast;

import uk.ac.ox.cs.diadem.oxpath.parse.OXPathParser;
import uk.ac.ox.cs.diadem.oxpath.parse.ast.custom.ASTOXPathActionPathCustom;

public class ASTOXPathActionPath extends ASTOXPathActionPathCustom {
  public ASTOXPathActionPath(final int id) {
    super(id);
  }

  public ASTOXPathActionPath(final OXPathParser p, final int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  @Override
  public Object jjtAccept(final OXPathParserVisitor visitor, final Object data)
      throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=1f73bd3b1367729986291d383e3da5f7 (do not edit this line) */
