/* Generated By:JJTree: Do not edit this line. ASTOXPathNodeTestOp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.ox.cs.diadem.oxpath.parse.ast;

import uk.ac.ox.cs.diadem.oxpath.parse.OXPathParser;

public class ASTOXPathNodeTestOp extends uk.ac.ox.cs.diadem.oxpath.parse.ast.custom.ASTOXPathNodeTestOpCustom {
  public ASTOXPathNodeTestOp(final int id) {
    super(id);
  }

  public ASTOXPathNodeTestOp(final OXPathParser p, final int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  @Override
  public Object jjtAccept(final OXPathParserVisitor visitor, final Object data)
      throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=88190d0019298695efbc48d306aa8a71 (do not edit this line) */
