/* Generated By:JJTree: Do not edit this line. ASTRelativeOXPathLocationPath.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.ox.cs.diadem.oxpath.parse.ast;

import uk.ac.ox.cs.diadem.oxpath.parse.OXPathParser;

public class ASTRelativeOXPathLocationPath extends
    uk.ac.ox.cs.diadem.oxpath.parse.ast.custom.ASTRelativeOXPathLocationPathCustom {
  public ASTRelativeOXPathLocationPath(final int id) {
    super(id);
  }

  public ASTRelativeOXPathLocationPath(final OXPathParser p, final int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  @Override
  public Object jjtAccept(final OXPathParserVisitor visitor, final Object data)
      throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2c3ec89519bfd117da5818eb9c6658ec (do not edit this line) */
