/* Generated By:JJTree: Do not edit this line. ASTXPathLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.ox.cs.diadem.oxpath.parse.ast;

import uk.ac.ox.cs.diadem.oxpath.parse.OXPathParser;

public class ASTXPathLiteral extends uk.ac.ox.cs.diadem.oxpath.parse.ast.custom.ASTXPathLiteralCustom {
  public ASTXPathLiteral(final int id) {
    super(id);
  }

  public ASTXPathLiteral(final OXPathParser p, final int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  @Override
  public Object jjtAccept(final OXPathParserVisitor visitor, final Object data)
      throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cad891b54effa094a2e27176b2572a5d (do not edit this line) */
