/* Generated By:JJTree: Do not edit this line. ASTXPathNumber.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.ox.cs.diadem.oxpath.parse.ast;

import uk.ac.ox.cs.diadem.oxpath.parse.OXPathParser;

public class ASTXPathNumber extends uk.ac.ox.cs.diadem.oxpath.parse.ast.custom.ASTXPathNumberCustom {
  public ASTXPathNumber(final int id) {
    super(id);
  }

  public ASTXPathNumber(final OXPathParser p, final int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  @Override
  public Object jjtAccept(final OXPathParserVisitor visitor, final Object data)
      throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d77c50737cacac944fa7a8696d0e2d5f (do not edit this line) */
