/* Generated By:JJTree: Do not edit this line. ASTXPathPrimaryExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package uk.ac.ox.cs.diadem.oxpath.parse.ast;

import uk.ac.ox.cs.diadem.oxpath.parse.OXPathParser;

public
class ASTXPathPrimaryExpr extends uk.ac.ox.cs.diadem.oxpath.parse.ast.custom.CustomSimpleNode {
  public ASTXPathPrimaryExpr(int id) {
    super(id);
  }

  public ASTXPathPrimaryExpr(OXPathParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(OXPathParserVisitor visitor, Object data) throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7530fe4649efb39643319f05b8e4ec7d (do not edit this line) */
