/* Generated By:JavaCC: Do not edit this line. OXPathParserVisitor.java Version 5.0 */
package uk.ac.ox.cs.diadem.oxpath.parse.ast;

public interface OXPathParserVisitor
{
  public Object visit(SimpleNode node, Object data) throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException;
  public Object visit(ASTExpression node, Object data) throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException;
  public Object visit(ASTRelativeOXPathLocationPath node, Object data) throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException;
  public Object visit(ASTSimpleOXPathStepPath node, Object data) throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException;
  public Object visit(ASTOXPathKleeneStarPath node, Object data) throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException;
  public Object visit(ASTOXPathActionPath node, Object data) throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException;
  public Object visit(ASTOXPathNodeTestOp node, Object data) throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException;
  public Object visit(ASTXPathLiteral node, Object data) throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException;
  public Object visit(ASTXPathPredicate node, Object data) throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException;
  public Object visit(ASTOXPathExtractionMarker node, Object data) throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException;
  public Object visit(ASTBinaryOpExpr node, Object data) throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException;
  public Object visit(ASTXPathUnaryExpr node, Object data) throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException;
  public Object visit(ASTXPathPrimaryExpr node, Object data) throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException;
  public Object visit(ASTXPathNumber node, Object data) throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException;
  public Object visit(ASTXPathFunctionCall node, Object data) throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException;
  public Object visit(ASTXPathPathExpr node, Object data) throws uk.ac.ox.cs.diadem.oxpath.core.OXPathException;
}
/* JavaCC - OriginalChecksum=969942dae9aa8d0421ecd1c79e9fd81a (do not edit this line) */
