var TextOrCommentNodeRepresentative=function(a,b){var c=a.parentNode;null===c&&(c=!1);return[a.data,c,b,a.ownerDocument.documentElement,_getXPathLocatorForConstructor(a),a.nodeType]},ElementNodeRepresentative=function(a){return[a,a.ownerDocument.documentElement,a.textContent,_getXPathLocatorForConstructor(a),a.nodeType]},AttributeNodeRepresentative=function(a){return[a.ownerElement,a.localName,a.nodeValue,a.ownerElement.ownerDocument.documentElement,a.nodeType]},DocumentNodeRepresentative=function(a,
b){return[a.documentElement,a.nodeType]},DocumentTypeRepresentative=function(a){return[a.ownerDocument.documentElement,a.nodeType]};function getNodeByXPath(a,b){try{var c=document.evaluate(a,b||document,null,XPathResult.FIRST_ORDERED_NODE_TYPE,null);return c?c.singleNodeValue:null}catch(d){return console.error("Error in getNodeByXPath(). Cause: "+d),null}}
function getNodesByXPath(a,b){try{for(var c=document.evaluate(a,b||document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null),d=[],e=0;e<c.snapshotLength;e++)d.push(c.snapshotItem(e));return d}catch(f){return console.error("Error in getNodesByXPath(). Cause: "+f),[]}}function findPositionAmongChildren(a,b){if(null===a)return-1;for(var c=a.childNodes,d=0;d<c.length;d++)if(c[d]===b)return d;return-1}
function testXPath(){for(var a=document.evaluate("//node()",document,null,XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null),b=[],c=0;c<a.snapshotLength;c++){var d=a.snapshotItem(c),e=document.evaluate("string(.)",d,null,XPathResult.STRING_TYPE,null).stringValue;d.textContent!==e&&b.push("Error: there are different -- node:"+_getXPathLocator(d))}return b}
function evalXPath(a,b,c,d,e){"undefined"===typeof d&&(d=!0);"undefined"===typeof e&&(e=!0);WebUtils.diademProperties.locatorUseIdAttribute=d;WebUtils.diademProperties.locatorUseClassAttribute=e;b=fromJava(b);a=document.evaluate(a,b,null,c,null);if(a.resultType===XPathResult.STRING_TYPE)return[a.stringValue];if(a.resultType===XPathResult.NUMBER_TYPE)return[a.numberValue];if(a===XPathResult.BOOLEAN_TYPE)return[a.booleanValue];if(a.resultType===XPathResult.UNORDERED_NODE_ITERATOR_TYPE||a.resultType===
XPathResult.ORDERED_NODE_ITERATOR_TYPE){c=[];try{for(var f=a.iterateNext();f;)c.push(toJava(f)),f=a.iterateNext();return c}catch(g){throw"Error: Document tree modified during iteration "+g;}}if(a.resultType===XPathResult.UNORDERED_NODE_SNAPSHOT_TYPE||a.resultType===XPathResult.ORDERED_NODE_SNAPSHOT_TYPE){c=[];for(f=0;f<a.snapshotLength;f++)b=a.snapshotItem(f),c.push(toJava(b));return c}if(a.resultType===XPathResult.ANY_UNORDERED_NODE_TYPE||a.resultType===XPathResult.FIRST_UNORDERED_NODE_TYPE)return c=
[],c.push(toJava(a.singleNodeValue)),c;throw"Error: Result Type not expected "+a.resultType;}
function evalXPathBulk(a,b,c,d,e){"undefined"===typeof d&&(d=!0);"undefined"===typeof e&&(e=!0);WebUtils.diademProperties.locatorUseIdAttribute=d;WebUtils.diademProperties.locatorUseClassAttribute=e;d={anchorNodes:[],contextualNodes:[],errors:[]};try{var f=evalXPath(a,b,XPathResult.ORDERED_NODE_ITERATOR_TYPE);d.anchorNodes=f;for(a=0;a<f.length;a++){var g=f[a];b=[];d.contextualNodes.push(b);for(e=0;e<c.length;e++)b.push(evalXPath(c[e],g,XPathResult.ORDERED_NODE_ITERATOR_TYPE))}}catch(h){d.errors.push(h.toString())}return d}
function log(a){"undefined"===typeof window.private_log&&(window.private_log=[]);window.private_log.push(a)}function takeLog(){if("undefined"===typeof window.private_log)return[];var a=private_log;window.private_log=[];return a}
var WebUtils={diademProperties:{locatorUseIdAttribute:!0,locatorUseClassAttribute:!0},diademNS:"_diadem",allowedFormTags:"FORM INPUT TEXTAREA LABEL FIELDSET LEGEND SELECT OPTGROUP OPTION BUTTON DATALIST KEYGEN OUTPUT".split(" "),fieldTags:["INPUT","TEXTAREA","SELECT","BUTTON","KEYGEN"],monitoredAttributes:[],monitoredElements:[],arrayContains:function(a,b){for(var c=0;c<a.length;c++)if(a[c]===b)return!0;return!1},isOptionTag:function(a){return a?"OPTION"===a.toUpperCase():!1},isOptionNode:function(a){if(!a)throw"node is undefined in calling WebUtils.isOptionNode";
var b=a.nodeName;b||(b=a.tagName);return b?"OPTION"===b.toUpperCase():!1},isFieldTag:function(a){return a?WebUtils.arrayContains(WebUtils.fieldTags,a):!1},isWhiteSpace:function(a){return/^\s+$/.test(a)},containsNonWord:function(a){return/\W/.test(a)},isInteger:function(a){return/^\d+$/.test(a)},startWithInteger:function(a){return/^\d/.test(a)},isMonitoredAttribute:function(a){return WebUtils.arrayContains(WebUtils.monitoredAttributes,a)},isMonitoredElement:function(a){return WebUtils.arrayContains(WebUtils.monitoredElements,
a)},findFieldOfOption:function(a){if(!a)return null;a=a.parentNode;if(!a)return null;var b=a.nodeName;if("SELECT"===b)return a;if("OPTGROUP"===b){a=a.parentNode;if(!a)return null;if("SELECT"===a.nodeName)return a}else if("DATALIST"===b&&(a=a.getAttribute("id")))return getNodeByXPath("//*[@list='"+a+"']");return null},findFieldsOfFieldset:function(a){return"FIELDSET"!==a.nodeName?null:getNodesByXPath("./descendant::*",a).filter(function(a){return WebUtils.isFieldTag(a.nodeName)})},findAncestorByTagName:function(a,
b){return getNodeByXPath("./ancestor::*[local-name()='"+b.toLowerCase()+"']",a)},Pair:function(a,b){return[a,b]}};
function toJava(a){if(null===a)return null;if(a.nodeType===Node.ELEMENT_NODE)return new ElementNodeRepresentative(a);if(a.nodeType===Node.TEXT_NODE||a.nodeType===Node.COMMENT_NODE)return new TextOrCommentNodeRepresentative(a,findPositionAmongChildren(a.parentNode,a));if(2==a.nodeType)return new AttributeNodeRepresentative(a);if(9===a.nodeType)return new DocumentNodeRepresentative(a);if(a.nodeType===Node.DOCUMENT_TYPE_NODE)return new DocumentTypeRepresentative(a);throw"Unsupported serialization for nodeType <"+
a.nodeType+">";}
function fromJava(a){var b=Object.prototype.toString;if("[object Object]"!==b.call(a)&&"[object Array]"!==b.call(a))throw"Expected DomNode or Array, but got <"+b.call(a)+">";b=a[a.length-1];if(b===Node.ELEMENT_NODE)return a[0];if(b===Node.DOCUMENT_NODE)return a[0].ownerDocument;if(b===Node.DOCUMENT_TYPE_NODE)return a[0].ownerDocument.doctype;if(b===Node.TEXT_NODE||b===Node.COMMENT_NODE)return a[0].childNodes[a[1]];if(b===Node.ATTRIBUTE_NODE){b=a[0].attributes.getNamedItem(a[1]);if(!b)throw"cannot find attribute node <"+a[1]+
">";return b}throw"Cannot resolve node: unsupported nodeType <"+b+">";}function _clog(a){console.log(JSON.stringify(a,null,4))}function throwUndefinedProperty(a,b){throw"Undefined property: "+a+" on eleTextOrCommentNodeRepresentativement "+b;}function escapelocalname(a){return WebUtils.containsNonWord(a.localName)?"*[local-name()='"+a.localName.toLowerCase()+"']":a.localName.toLowerCase()}
function _createXPathFromElement(a,b,c){var d=document.getElementsByTagName("*");for(segs=[];a&&a.nodeType===Node.ELEMENT_NODE;a=a.parentNode){if(a===document.documentElement)return segs.unshift("/"+a.nodeName.toLowerCase()+"[1]"),segs.join("/");if("body"===a.nodeName.toLowerCase())segs.unshift(a.nodeName.toLowerCase()+"[1]");else{var e=a.hasAttribute("id")&&0<a.getAttribute("id").length&&!a.getAttribute("id").contains("'")&&!a.getAttribute("id").contains(" "),f=a.hasAttribute("class")&&0<a.getAttribute("class").length&&
!a.getAttribute("class").contains("'")&&1>=a.getAttribute("class").trim().replace(/\s+/g," ").split(" ").length-1;if(b&&e){for(f=e=0;f<d.length&&!(d[f].hasAttribute("id")&&d[f].id===a.id&&e++,1<e);f++);if(1===e)return segs.unshift("id('"+a.getAttribute("id")+"')"),segs.join("/");ii=1;for(sibl=a.previousSibling;sibl;sibl=sibl.previousSibling)sibl.localName===a.localName&&ii++;segs.unshift(escapelocalname(a)+"["+ii+"]")}else if(c&&f){i=1;for(sib=a.previousSibling;sib;sib=sib.previousSibling)sib.localName===
a.localName&&sib.hasAttribute("class")&&sib.getAttribute("class")===a.getAttribute("class")&&i++;e=a.getAttribute("class");f=e.trim().replace(/\s+/g," ");e=f==e?"[@class='"+e+"']":"[normalize-space(@class)='"+f+"']";segs.unshift(escapelocalname(a)+e+"["+i+"]")}else{i=1;for(sib=a.previousSibling;sib;sib=sib.previousSibling)sib.localName===a.localName&&i++;segs.unshift(escapelocalname(a)+"["+i+"]")}}}console.log(segs);return segs.length?"/"+segs.join("/"):null}
function _createXPathFromTextNode(a,b,c){b=_createXPathFromElement(a.parentNode,b,c);i=1;for(sib=a.previousSibling;sib;sib=sib.previousSibling)sib.nodeName===a.nodeName&&i++;return b+"/text()["+i+"]"}function _createXPathFromAttributeNode(a,b,c){return _createXPathFromElement(a.ownerElement,b,c)+"/@"+escapelocalname(a)}function getCssPropertyValue(a,b){return window.getComputedStyle?window.getComputedStyle(a,null).getPropertyValue(b):a.currentStyle.getAttribute(b)}
function getDocumentDimension(){var a=document.body,b=document.documentElement,c=Math.max(a.scrollHeight,a.offsetHeight,b.clientHeight,b.scrollHeight,b.offsetHeight);return[Math.max(a.scrollWidth,a.offsetWidth,b.clientWidth,b.scrollWidth,b.offsetWidth),c]}function getXPathLocator(a,b,c){a=fromJava(a);"undefined"===typeof b&&(b=!0);"undefined"===typeof c&&(c=!0);WebUtils.diademProperties.locatorUseIdAttribute=b;WebUtils.diademProperties.locatorUseClassAttribute=c;return _getXPathLocator(a,b,c)}
function _getXPathLocatorForConstructor(a){return _getXPathLocator(a,WebUtils.diademProperties.locatorUseIdAttribute,WebUtils.diademProperties.locatorUseClassAttribute)}function _getXPathLocator(a,b,c){return a.nodeType===Node.DOCUMENT_NODE?"/":a.nodeType===Node.ELEMENT_NODE?_createXPathFromElement(a,b,c):a.nodeType===Node.TEXT_NODE?_createXPathFromTextNode(a,b,c):a.nodeType===Node.ATTRIBUTE_NODE?_createXPathFromAttributeNode(a,b,c):null};