var bot_dom_isShown=function(a,b){function c(a){if("none"==bot_dom_getEffectiveStyle(a,"display"))return!1;a=bot_dom_getParentElement(a);return!a||c(a)}function d(a){var b=bot_dom_getClientRect(a);return 0<b.height&&0<b.width?!0:bot_dom_isElement(a,"PATH")&&(0<b.height||0<b.width)?(a=bot_dom_getEffectiveStyle(a,"stroke-width"),!!a&&0<parseInt(a,10)):"hidden"!=bot_dom_getEffectiveStyle(a,"overflow")&&goog_array_some(a.childNodes,function(a){return a.nodeType==Node.TEXT_NODE||bot_dom_isElement(a)&&
d(a)})}function f(a){return bot_dom_getOverflowState(a)==bot_dom_OverflowState.HIDDEN&&goog_array_every(a.childNodes,function(a){return!bot_dom_isElement(a)||f(a)})}if(!bot_dom_isElement(a))throw Error("Argument to isShown must be of type Element");if(bot_dom_isElement(a,"OPTION")||bot_dom_isElement(a,"OPTGROUP")){var e=goog_dom_getAncestor(a,function(a){return bot_dom_isElement(a,"SELECT")});return!!e&&bot_dom_isShown(e,!0)}return(e=bot_dom_maybeFindImageMap_(a))?!!e.image&&0<e.rect.width&&0<e.rect.height&&
bot_dom_isShown(e.image,b):bot_dom_isElement(a,"INPUT")&&"hidden"==a.type.toLowerCase()||bot_dom_isElement(a,"NOSCRIPT")||"hidden"==bot_dom_getEffectiveStyle(a,"visibility")||!c(a)||!b&&0==bot_dom_getOpacity(a)||!d(a)?!1:!f(a)},bot_dom_isInParentOverflow=function(a,b){var c=goog_style_getOffsetParent(a),d=bot_dom_getParentElement(a);bot_dom_isElement(d,"BODY")&&(c=d);if(c&&("scroll"==bot_dom_getEffectiveStyle(c,"overflow")||"auto"==bot_dom_getEffectiveStyle(c,"overflow"))){var d=bot_dom_getElementSize(c),
f=goog_style_getClientPosition(c),e=goog_style_getClientPosition(a),g,h;b?(g=b.x,h=b.y):(h=bot_dom_getElementSize(a),g=h.width/2,h=h.height/2);g=e.x+g;e=e.y+h;return g>=f.x+d.width||g<=f.x||e>=f.y+d.height||e<=f.y?!0:bot_dom_isInParentOverflow(c)}return!1},bot_dom_getElementSize=function(a){if(goog_isFunction(a.getBBox))try{var b=a.getBBox();if(b)return b}catch(c){}return bot_dom_isElement(a,"BODY")?(b=goog_dom_getOwnerDocument(a),b=goog_dom_getWindow(b)||void 0,bot_dom_isBodyScrollBarShown_(a)?bot_window_getInteractableSize(b):
goog_dom_getViewportSize(b)):goog_style_getSize(a)},bot_window_getInteractableSize=function(a){var b=(a||bot_getWindow()).document;a=b.documentElement;var c=b.body,b=[a.clientHeight,a.scrollHeight,a.offsetHeight,c.scrollHeight,c.offsetHeight],d=function(a,b){return a-b};a=goog_array_peek([a.clientWidth,a.scrollWidth,a.offsetWidth,c.scrollWidth,c.offsetWidth].sort(d))||0;b=goog_array_peek(b.sort(d))||0;return new goog_math.Size(a,b)},bot_dom_getClientRect=function(a){var b=bot_dom_maybeFindImageMap_(a);
if(b)return b.rect;if(bot_dom_isElement(a,"HTML"))return a=goog_dom_getOwnerDocument(a),a=goog_dom_getViewportSize(goog_dom_getWindow(a)),new goog_math_Rect(0,0,a.width,a.height);var c;try{c=a.getBoundingClientRect()}catch(d){return new goog_math_Rect(0,0,0,0)}return new goog_math_Rect(c.left,c.top,c.right-c.left,c.bottom-c.top)},bot_dom_trimExcludingNonBreakingSpaceCharacters_=function(a){return a.replace(/^[^\S\xa0]+|[^\S\xa0]+$/g,"")},bot_dom_getOpacity=function(a){return bot_dom_getOpacityNonIE_(a)},
bot_dom_getOpacityNonIE_=function(a){var b=1,c=bot_dom_getEffectiveStyle(a,"opacity");c&&(b=Number(c));(a=bot_dom_getParentElement(a))&&(b*=bot_dom_getOpacityNonIE_(a));return b},bot_dom_isBodyScrollBarShown_=function(a){bot_dom_isElement(a,"BODY");if("hidden"!=bot_dom_getEffectiveStyle(a,"overflow"))return!0;a=bot_dom_getParentElement(a);if(!a||!bot_dom_isElement(a,"HTML"))return!0;a=bot_dom_getEffectiveStyle(a,"overflow");return"auto"==a||"scroll"==a},bot_dom_getParentElement=function(a){for(a=
a.parentNode;a&&a.nodeType!=Node.ELEMENT_NODE&&a.nodeType!=Node.DOCUMENT_NODE&&a.nodeType!=Node.DOCUMENT_FRAGMENT_NODE;)a=a.parentNode;return bot_dom_isElement(a)?a:null},bot_dom_getVisibleText=function(a){var b=[];bot_dom_appendVisibleTextLinesFromElement_(a,b);b=goog_array_map(b,bot_dom_trimExcludingNonBreakingSpaceCharacters_);a=b.join("\n");return bot_dom_trimExcludingNonBreakingSpaceCharacters_(a).replace(/\xa0/g," ")},bot_dom_appendVisibleTextLinesFromElement_=function(a,b){if(bot_dom_isElement(a,
"BR"))b.push("");else{var c=bot_dom_isElement(a,"TD"),d=bot_dom_getEffectiveStyle(a,"display"),f=!c&&!goog_array_contains(bot_dom_INLINE_DISPLAY_BOXES_,d),e=goog_dom_getPreviousElementSibling(a),e=e?bot_dom_getEffectiveStyle(e,"display"):"",g=bot_dom_getEffectiveStyle(a,"float")||bot_dom_getEffectiveStyle(a,"cssFloat")||bot_dom_getEffectiveStyle(a,"styleFloat");!f||"run-in"==e&&"none"==g||goog_string_isEmpty(goog_array_peek(b)||"")||b.push("");var h=bot_dom_isShown(a),p=null,q=null;h&&(p=bot_dom_getEffectiveStyle(a,
"white-space"),q=bot_dom_getEffectiveStyle(a,"text-transform"));goog_array_forEach(a.childNodes,function(a){a.nodeType==Node.TEXT_NODE&&h?bot_dom_appendVisibleTextLinesFromTextNode_(a,b,p,q):bot_dom_isElement(a)&&bot_dom_appendVisibleTextLinesFromElement_(a,b)});e=goog_array_peek(b)||"";!c&&"table-cell"!=d||!e||goog_string_endsWith(e," ")||(b[b.length-1]+=" ");f&&"run-in"!=d&&!goog_string_isEmpty(e)&&b.push("")}};
bot_dom_appendVisibleTextLinesFromTextNode_=function(a,b,c,d){a=a.nodeValue.replace(/[\u200b\u200e\u200f]/g,"");a=goog_string_canonicalizeNewlines(a);if("normal"==c||"nowrap"==c)a=a.replace(/\n/g," ");a="pre"==c||"pre-wrap"==c?a.replace(/[ \f\t\v\u2028\u2029]/g,"\u00a0"):a.replace(/[\ \f\t\v\u2028\u2029]+/g," ");"capitalize"==d?a=a.replace(/(^|\s)(\S)/g,function(a,b,c){return b+c.toUpperCase()}):"uppercase"==d?a=a.toUpperCase():"lowercase"==d&&(a=a.toLowerCase());c=b.pop()||"";goog_string_endsWith(c,
" ")&&goog_string_startsWith(a," ")&&(a=a.substr(1));b.push(c+a)};
var goog_string_canonicalizeNewlines=function(a){return a.replace(/(\r\n|\r|\n)/g,"\n")},goog_string_endsWith=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c},bot_dom_INLINE_DISPLAY_BOXES_="inline inline-block inline-table none table-cell table-column table-column-group".split(" "),goog_array_forEach=function(a,b,c){for(var d=a.length,f=goog_isString(a)?a.split(""):a,e=0;e<d;e++)e in f&&b.call(c,f[e],e,a)},goog_string_isEmpty=function(a){return/^[\s\xa0]*$/.test(a)},goog_dom_getPreviousElementSibling=
function(a){return void 0!=a.previousElementSibling?a.previousElementSibling:goog_dom_getNextElementNode_(a.previousSibling,!1)},goog_dom_getNextElementNode_=function(a,b){for(;a&&a.nodeType!=Node.ELEMENT_NODE;)a=b?a.nextSibling:a.previousSibling;return a},goog_array_contains=function(a,b){return 0<=goog_array_indexOf(a,b)},goog_array_indexOf=function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(goog_isString(a))return goog_isString(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in
a&&a[c]===b)return c;return-1},goog_dom_getOwnerDocument=function(a){return a.nodeType==Node.DOCUMENT_NODE?a:a.ownerDocument||a.document},bot_dom_isElement=function(a,b){return!!a&&1==a.nodeType&&(!b||a.tagName.toUpperCase()==b)},goog_dom_getAncestor=function(a,b,c,d){c||(a=a.parentNode);c=null==d;for(var f=0;a&&(c||f<=d);){if(b(a))return a;a=a.parentNode;f++}return null},bot_dom_getEffectiveStyle=function(a,b){var c=goog_string_toCamelCase(b);if("float"==c||"cssFloat"==c||"styleFloat"==c)c="cssFloat";
var d=goog_style_getComputedStyle(a,c)||bot_dom_getCascadedStyle_(a,c);return null===d?null:bot_color_standardizeColor(c,d)},goog_style_getComputedStyle=function(a,b){var c=goog_dom_getOwnerDocument(a);return c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))?c[b]||c.getPropertyValue(b)||"":""},bot_dom_getCascadedStyle_=function(a,b){var c=a.currentStyle||a.style,d=c[b];!goog_isDef(d)&&goog_isFunction(c.getPropertyValue)&&(d=c.getPropertyValue(b));return"inherit"!=
d?goog_isDef(d)?d:null:(c=bot_dom_getParentElement(a))?bot_dom_getCascadedStyle_(c,b):null},goog_isDef=function(a){return void 0!==a},goog_string_toCamelCase=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})},bot_dom_maybeFindImageMap_=function(a){var b=bot_dom_isElement(a,"MAP");if(!b&&!bot_dom_isElement(a,"AREA"))return null;var c=b?a:bot_dom_isElement(a.parentNode,"MAP")?a.parentNode:null,d=null,f=null;if(c&&c.name&&(d=goog_dom_getOwnerDocument(c),d=getNodeByXPath('/descendant::*[@usemap = "#'+
c.name+'"]',d))&&(f=bot_dom_getClientRect(d),!b&&"default"!=a.shape.toLowerCase())){var e=bot_dom_getAreaRelativeRect_(a);a=Math.min(Math.max(e.left,0),f.width);b=Math.min(Math.max(e.top,0),f.height);c=Math.min(e.width,f.width-a);e=Math.min(e.height,f.height-b);f=new goog_math_Rect(a+f.left,b+f.top,c,e)}return{image:d,rect:f||new goog_math_Rect(0,0,0,0)}},bot_dom_getAreaRelativeRect_=function(a){var b=a.shape.toLowerCase();a=a.coords.split(",");if("rect"==b&&4==a.length){var b=a[0],c=a[1];return new goog_math_Rect(b,
c,a[2]-b,a[3]-c)}if("circle"==b&&3==a.length)return b=a[2],new goog_math_Rect(a[0]-b,a[1]-b,2*b,2*b);if("poly"==b&&2<a.length){for(var b=a[0],c=a[1],d=b,f=c,e=2;e+1<a.length;e+=2)b=Math.min(b,a[e]),d=Math.max(d,a[e]),c=Math.min(c,a[e+1]),f=Math.max(f,a[e+1]);return new goog_math_Rect(b,c,d-b,f-c)}return new goog_math_Rect(0,0,0,0)},bot_dom_getOverflowState=function(a,b){function c(a){function b(a){if(a==h)return!0;var d=bot_dom_getEffectiveStyle(a,"display");return goog_string_startsWith(d,"inline")||
"absolute"==c&&"static"==bot_dom_getEffectiveStyle(a,"position")?!1:!0}var c=bot_dom_getEffectiveStyle(a,"position");if("fixed"==c)return t=!0,a==h?null:h;for(a=bot_dom_getParentElement(a);a&&!b(a);)a=bot_dom_getParentElement(a);return a}function d(a){var b=a;if("visible"==q)if(a==h&&p)b=p;else if(a==p)return{x:"visible",y:"visible"};b={x:bot_dom_getEffectiveStyle(b,"overflow-x"),y:bot_dom_getEffectiveStyle(b,"overflow-y")};a==h&&(b.x="visible"==b.x?"auto":b.x,b.y="visible"==b.y?"auto":b.y);return b}
function f(a){return a==h?(new goog_dom_DomHelper(g)).getDocumentScroll():new goog_math_Coordinate(a.scrollLeft,a.scrollTop)}for(var e=bot_dom_getClientRegion(a,b),g=goog_dom_getOwnerDocument(a),h=g.documentElement,p=g.body,q=bot_dom_getEffectiveStyle(h,"overflow"),t,m=c(a);m;m=c(m)){var k=d(m);if("visible"!=k.x||"visible"!=k.y){var l=bot_dom_getClientRect(m);if(0==l.width||0==l.height)return bot_dom_OverflowState.HIDDEN;var n=e.right<l.left,r=e.bottom<l.top;if(n&&"hidden"==k.x||r&&"hidden"==k.y)return bot_dom_OverflowState.HIDDEN;
if(n&&"visible"!=k.x||r&&"visible"!=k.y){n=f(m);r=e.bottom<l.top-n.y;if(e.right<l.left-n.x&&"visible"!=k.x||r&&"visible"!=k.x)return bot_dom_OverflowState.HIDDEN;e=bot_dom_getOverflowState(m);return e==bot_dom_OverflowState.HIDDEN?bot_dom_OverflowState.HIDDEN:bot_dom_OverflowState.SCROLL}n=e.left>=l.left+l.width;l=e.top>=l.top+l.height;if(n&&"hidden"==k.x||l&&"hidden"==k.y)return bot_dom_OverflowState.HIDDEN;if(n&&"visible"!=k.x||l&&"visible"!=k.y){if(t&&(k=f(m),e.left>=h.scrollWidth-k.x||e.right>=
h.scrollHeight-k.y))return bot_dom_OverflowState.HIDDEN;e=bot_dom_getOverflowState(m);return e==bot_dom_OverflowState.HIDDEN?bot_dom_OverflowState.HIDDEN:bot_dom_OverflowState.SCROLL}}}return bot_dom_OverflowState.NONE},goog_string_startsWith=function(a,b){return 0==a.lastIndexOf(b,0)},bot_dom_getClientRegion=function(a,b){var c=bot_dom_getClientRect(a).toBox();if(b){var d=b instanceof goog_math_Rect?b:new goog_math_Rect(b.x,b.y,1,1);c.left=goog_math_clamp(c.left+d.left,c.left,c.right);c.top=goog_math_clamp(c.top+
d.top,c.top,c.bottom);c.right=goog_math_clamp(c.left+d.width,c.left,c.right);c.bottom=goog_math_clamp(c.top+d.height,c.top,c.bottom)}return c},bot_dom_DISABLED_ATTRIBUTE_SUPPORTED_="BUTTON INPUT OPTGROUP OPTION SELECT TEXTAREA FIELDSET".split(" "),bot_dom_getProperty=function(a,b){return a[b]},bot_dom_isEnabled=function(a){var b=a.tagName.toUpperCase();return goog_array_contains(bot_dom_DISABLED_ATTRIBUTE_SUPPORTED_,b)?bot_dom_getProperty(a,"disabled")?!1:a.parentNode&&a.parentNode.nodeType==Node.ELEMENT_NODE&&
"OPTGROUP"==b||"OPTION"==b?bot_dom_isEnabled(a.parentNode):!goog_dom_getAncestor(a,function(a){var b=a.parentNode;if(b&&bot_dom_isElement(b,"FIELDSET")&&bot_dom_getProperty(b,"disabled")){if(!bot_dom_isElement(a,"LEGEND"))return!0;for(;a=goog_dom_getPreviousElementSibling(a);)if(bot_dom_isElement(a,"LEGEND"))return!0}return!1},!0):!0},goog_math_clamp=function(a,b,c){return Math.min(Math.max(a,b),c)},bot_dom_OverflowState={NONE:"none",HIDDEN:"hidden",SCROLL:"scroll"},goog_dom_DomHelper=function(a){this.document_=
a||goog_global.document||document};goog_dom_DomHelper.prototype.getDocumentScroll=function(){return goog_dom_getDocumentScroll_(this.document_)};var goog_dom_getDocumentScroll_=function(a){var b=goog_dom_getDocumentScrollElement_(a);a=goog_dom_getWindow_(a);return new goog_math_Coordinate(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)},goog_dom_getDocumentScrollElement=function(){return goog_dom_getDocumentScrollElement_(document)};goog_dom_getDocumentScrollElement_=function(a){return a.documentElement};
var goog_dom_findNode=function(a,b){var c=[];return goog_dom_findNodes_(a,b,c,!0)?c[0]:void 0},goog_dom_findNodes=function(a,b){var c=[];goog_dom_findNodes_(a,b,c,!1);return c},goog_dom_findNodes_=function(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||goog_dom_findNodes_(a,b,c,d))return!0;a=a.nextSibling}return!1},goog_array_some=function(a,b,c){for(var d=a.length,f=goog_isString(a)?a.split(""):a,e=0;e<d;e++)if(e in f&&b.call(c,f[e],e,a))return!0;return!1},goog_array_every=function(a,
b,c){for(var d=a.length,f=goog_isString(a)?a.split(""):a,e=0;e<d;e++)if(e in f&&!b.call(c,f[e],e,a))return!1;return!0},goog_style_getOffsetParent=function(a){var b=goog_dom_getOwnerDocument(a),c=goog_style_getStyle_(a,"position"),d="fixed"==c||"absolute"==c;for(a=a.parentNode;a&&a!=b;a=a.parentNode)if(c=goog_style_getStyle_(a,"position"),d=d&&"static"==c&&a!=b.documentElement&&a!=b.body,!d&&(a.scrollWidth>a.clientWidth||a.scrollHeight>a.clientHeight||"fixed"==c||"absolute"==c||"relative"==c))return a;
return null},goog_style_getStyle_=function(a,b){return goog_style_getComputedStyle(a,b)||goog_style_getCascadedStyle(a,b)||a.style&&a.style[b]},goog_style_getClientPosition=function(a){var b=new goog_math_Coordinate;if(a.nodeType==Node.ELEMENT_NODE){if(a.getBoundingClientRect){var c=goog_style_getBoundingClientRect_(a);b.x=c.left;b.y=c.top}else{var c=goog_dom_getDomHelper(a).getDocumentScroll(),d=goog_style_getPageOffset(a);b.x=d.x-c.x;b.y=d.y-c.y}b=goog_math_Coordinate_sum(b,goog_style_getCssTranslation(a))}else c=
goog_isFunction(a.getBrowserEvent),d=a,a.targetTouches?d=a.targetTouches[0]:c&&a.getBrowserEvent().targetTouches&&(d=a.getBrowserEvent().targetTouches[0]),b.x=d.clientX,b.y=d.clientY;return b},goog_style_getCssTranslation=function(a){var b;(b=goog_style_getStyle_(a,"-moz-transform"))||(b=goog_style_getStyle_(a,"transform"));return b?(a=b.match(goog_style_MATRIX_TRANSLATION_REGEX_))?new goog_math_Coordinate(parseFloat(a[1]),parseFloat(a[2])):new goog_math_Coordinate(0,0):new goog_math_Coordinate(0,
0)},goog_style_MATRIX_TRANSLATION_REGEX_=/matrix\([0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, [0-9\.\-]+, ([0-9\.\-]+)p?x?, ([0-9\.\-]+)p?x?\)/,goog_math_Coordinate_sum=function(a,b){return new goog_math_Coordinate(a.x+b.x,a.y+b.y)},goog_style_getBoundingClientRect_=function(a){return a.getBoundingClientRect()},goog_isString=function(a){return"string"==typeof a},goog_isFunction=function(a){return"function"==typeof a},goog_dom_getWindow=function(a){return a?goog_dom_getWindow_(a):window},goog_dom_getWindow_=
function(a){return a.parentWindow||a.defaultView},goog_dom_getViewportSize=function(a){return goog_dom_getViewportSize_(a||window)},goog_dom_getViewportSize_=function(a){a=a.document.documentElement;return new goog_math_Size(a.clientWidth,a.clientHeight)},goog_style_getSize=function(a){if("none"!=goog_style_getStyle_(a,"display"))return goog_style_getSizeWithDisplay_(a);var b=a.style,c=b.display,d=b.visibility,f=b.position;b.visibility="hidden";b.position="absolute";b.display="inline";a=goog_style_getSizeWithDisplay_(a);
b.display=c;b.position=f;b.visibility=d;return a},goog_style_getSizeWithDisplay_=function(a){var b=a.offsetWidth,c=a.offsetHeight;return!goog_isDef(b)&&a.getBoundingClientRect?(a=goog_style_getBoundingClientRect_(a),new goog_math_Size(a.right-a.left,a.bottom-a.top)):new goog_math_Size(b,c)},goog_array_peek=function(a){return a[a.length-1]},bot_getWindow=function(){return window},goog_array_map=function(a,b,c){for(var d=a.length,f=Array(d),e=goog_isString(a)?a.split(""):a,g=0;g<d;g++)g in e&&(f[g]=
b.call(c,e[g],g,a));return f},goog_math_Size=function(a,b){this.width=a;this.height=b},goog_math_Rect=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};goog_math_Rect.prototype.clone=function(){return new goog_math_Rect(this.left,this.top,this.width,this.height)};goog_math_Rect.prototype.toBox=function(){return new goog_math_Box(this.top,this.left+this.width,this.top+this.height,this.left)};
var goog_math_Coordinate=function(a,b){this.x=goog_isDef(a)?a:0;this.y=goog_isDef(b)?b:0},goog_math_Box=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d},bot_color_standardizeColor=function(a,b){return bot_color_isColorProperty(a)&&bot_color_isConvertibleColor(b)?bot_color_standardizeToRgba_(b):b},bot_color_standardizeToRgba_=function(a){var b=bot_color_parseRgbaColor(a);b.length||(b=bot_color_convertToRgba_(a),bot_color_addAlphaIfNecessary_(b));return 4!=b.length?a:bot_color_toRgbaStyle_(b)},
bot_color_convertToRgba_=function(a){var b=bot_color_parseRgbColor_(a);if(b.length)return b;b=(b=goog_color_names[a.toLowerCase()])?b:bot_color_prependHashIfNecessary_(a);return bot_color_isValidHexColor_(b)&&(b=bot_color_hexToRgb(bot_color_normalizeHex(b)),b.length)?b:[]},bot_color_isConvertibleColor=function(a){return!!(bot_color_isValidHexColor_(bot_color_prependHashIfNecessary_(a))||bot_color_parseRgbColor_(a).length||goog_color_names&&goog_color_names[a.toLowerCase()]||bot_color_parseRgbaColor(a).length)},
bot_color_COLOR_PROPERTIES_="background-color border-top-color border-right-color border-bottom-color border-left-color color outline-color".split(" "),bot_color_isColorProperty=function(a){return goog_array_contains(bot_color_COLOR_PROPERTIES_,a)},bot_color_HEX_TRIPLET_RE_=/#([0-9a-fA-F])([0-9a-fA-F])([0-9a-fA-F])/,bot_color_normalizeHex=function(a){if(!bot_color_isValidHexColor_(a))throw Error("'"+a+"' is not a valid hex color");4==a.length&&(a=a.replace(bot_color_HEX_TRIPLET_RE_,"#$1$1$2$2$3$3"));
return a.toLowerCase()},bot_color_hexToRgb=function(a){a=bot_color_normalizeHex(a);var b=parseInt(a.substr(1,2),16),c=parseInt(a.substr(3,2),16);a=parseInt(a.substr(5,2),16);return[b,c,a]},bot_color_VALID_HEX_COLOR_RE_=/^#(?:[0-9a-f]{3}){1,2}$/i,bot_color_isValidHexColor_=function(a){return bot_color_VALID_HEX_COLOR_RE_.test(a)},bot_color_NORMALIZED_HEX_COLOR_RE_=/^#[0-9a-f]{6}$/,bot_color_isNormalizedHexColor_=function(a){return bot_color_NORMALIZED_HEX_COLOR_RE_.test(a)},bot_color_RGBA_COLOR_RE_=
/^(?:rgba)?\((\d{1,3}),\s?(\d{1,3}),\s?(\d{1,3}),\s?(0|1|0\.\d*)\)$/i,bot_color_parseRgbaColor=function(a){var b=a.match(bot_color_RGBA_COLOR_RE_);if(b){a=Number(b[1]);var c=Number(b[2]),d=Number(b[3]),b=Number(b[4]);if(0<=a&&255>=a&&0<=c&&255>=c&&0<=d&&255>=d&&0<=b&&1>=b)return[a,c,d,b]}return[]},bot_color_RGB_COLOR_RE_=/^(?:rgb)?\((0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2}),\s?(0|[1-9]\d{0,2})\)$/i,bot_color_parseRgbColor_=function(a){var b=a.match(bot_color_RGB_COLOR_RE_);if(b){a=Number(b[1]);var c=Number(b[2]),
b=Number(b[3]);if(0<=a&&255>=a&&0<=c&&255>=c&&0<=b&&255>=b)return[a,c,b]}return[]},bot_color_prependHashIfNecessary_=function(a){return"#"==a.charAt(0)?a:"#"+a},bot_color_addAlphaIfNecessary_=function(a){3==a.length&&a.push(1);return a},bot_color_toRgbaStyle_=function(a){return"rgba("+a.join(", ")+")"},goog_color_names={aliceblue:"#f0f8ff",antiquewhite:"#faebd7",aqua:"#00ffff",aquamarine:"#7fffd4",azure:"#f0ffff",beige:"#f5f5dc",bisque:"#ffe4c4",black:"#000000",blanchedalmond:"#ffebcd",blue:"#0000ff",
blueviolet:"#8a2be2",brown:"#a52a2a",burlywood:"#deb887",cadetblue:"#5f9ea0",chartreuse:"#7fff00",chocolate:"#d2691e",coral:"#ff7f50",cornflowerblue:"#6495ed",cornsilk:"#fff8dc",crimson:"#dc143c",cyan:"#00ffff",darkblue:"#00008b",darkcyan:"#008b8b",darkgoldenrod:"#b8860b",darkgray:"#a9a9a9",darkgreen:"#006400",darkgrey:"#a9a9a9",darkkhaki:"#bdb76b",darkmagenta:"#8b008b",darkolivegreen:"#556b2f",darkorange:"#ff8c00",darkorchid:"#9932cc",darkred:"#8b0000",darksalmon:"#e9967a",darkseagreen:"#8fbc8f",
darkslateblue:"#483d8b",darkslategray:"#2f4f4f",darkslategrey:"#2f4f4f",darkturquoise:"#00ced1",darkviolet:"#9400d3",deeppink:"#ff1493",deepskyblue:"#00bfff",dimgray:"#696969",dimgrey:"#696969",dodgerblue:"#1e90ff",firebrick:"#b22222",floralwhite:"#fffaf0",forestgreen:"#228b22",fuchsia:"#ff00ff",gainsboro:"#dcdcdc",ghostwhite:"#f8f8ff",gold:"#ffd700",goldenrod:"#daa520",gray:"#808080",green:"#008000",greenyellow:"#adff2f",grey:"#808080",honeydew:"#f0fff0",hotpink:"#ff69b4",indianred:"#cd5c5c",indigo:"#4b0082",
ivory:"#fffff0",khaki:"#f0e68c",lavender:"#e6e6fa",lavenderblush:"#fff0f5",lawngreen:"#7cfc00",lemonchiffon:"#fffacd",lightblue:"#add8e6",lightcoral:"#f08080",lightcyan:"#e0ffff",lightgoldenrodyellow:"#fafad2",lightgray:"#d3d3d3",lightgreen:"#90ee90",lightgrey:"#d3d3d3",lightpink:"#ffb6c1",lightsalmon:"#ffa07a",lightseagreen:"#20b2aa",lightskyblue:"#87cefa",lightslategray:"#778899",lightslategrey:"#778899",lightsteelblue:"#b0c4de",lightyellow:"#ffffe0",lime:"#00ff00",limegreen:"#32cd32",linen:"#faf0e6",
magenta:"#ff00ff",maroon:"#800000",mediumaquamarine:"#66cdaa",mediumblue:"#0000cd",mediumorchid:"#ba55d3",mediumpurple:"#9370db",mediumseagreen:"#3cb371",mediumslateblue:"#7b68ee",mediumspringgreen:"#00fa9a",mediumturquoise:"#48d1cc",mediumvioletred:"#c71585",midnightblue:"#191970",mintcream:"#f5fffa",mistyrose:"#ffe4e1",moccasin:"#ffe4b5",navajowhite:"#ffdead",navy:"#000080",oldlace:"#fdf5e6",olive:"#808000",olivedrab:"#6b8e23",orange:"#ffa500",orangered:"#ff4500",orchid:"#da70d6",palegoldenrod:"#eee8aa",
palegreen:"#98fb98",paleturquoise:"#afeeee",palevioletred:"#db7093",papayawhip:"#ffefd5",peachpuff:"#ffdab9",peru:"#cd853f",pink:"#ffc0cb",plum:"#dda0dd",powderblue:"#b0e0e6",purple:"#800080",red:"#ff0000",rosybrown:"#bc8f8f",royalblue:"#4169e1",saddlebrown:"#8b4513",salmon:"#fa8072",sandybrown:"#f4a460",seagreen:"#2e8b57",seashell:"#fff5ee",sienna:"#a0522d",silver:"#c0c0c0",skyblue:"#87ceeb",slateblue:"#6a5acd",slategray:"#708090",slategrey:"#708090",snow:"#fffafa",springgreen:"#00ff7f",steelblue:"#4682b4",
tan:"#d2b48c",teal:"#008080",thistle:"#d8bfd8",tomato:"#ff6347",turquoise:"#40e0d0",violet:"#ee82ee",wheat:"#f5deb3",white:"#ffffff",whitesmoke:"#f5f5f5",yellow:"#ffff00",yellowgreen:"#9acd32"};