var __extends=this.__extends||function(b,a){function e(){this.constructor=b}for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);e.prototype=a.prototype;b.prototype=new e},MutationObserverCtor;MutationObserverCtor="undefined"!==typeof WebKitMutationObserver?WebKitMutationObserver:MutationObserver;
if(void 0===MutationObserverCtor)throw console.error("DOM Mutation Observers are required."),console.error("https://developer.mozilla.org/en-US/docs/DOM/MutationObserver"),Error("DOM Mutation Observers are required");
var NodeMap=function(){function b(){this.nodes=[];this.values=[]}b.prototype.nodeId=function(a){var e=a[b.ID_PROP];e||(e=a[b.ID_PROP]=b.nextId_++);return e};b.prototype.set=function(a,e){var c=this.nodeId(a);this.nodes[c]=a;this.values[c]=e};b.prototype.get=function(a){a=this.nodeId(a);return this.values[a]};b.prototype.has=function(a){return this.nodeId(a)in this.nodes};b.prototype["delete"]=function(a){a=this.nodeId(a);delete this.nodes[a];this.values[a]=void 0};b.prototype.keys=function(){var a=
[],e;for(e in this.nodes)a.push(this.nodes[e]);return a};b.ID_PROP="__mutation_summary_node_map_id__";b.nextId_=1;return b}(),Movement;(function(b){b[b.STAYED_OUT=0]="STAYED_OUT";b[b.ENTERED=1]="ENTERED";b[b.STAYED_IN=2]="STAYED_IN";b[b.REPARENTED=3]="REPARENTED";b[b.REORDERED=4]="REORDERED";b[b.EXITED=5]="EXITED"})(Movement||(Movement={}));function enteredOrExited(b){return b===Movement.ENTERED||b===Movement.EXITED}
var NodeChange=function(){function b(a,e,c,d,b,f,g,m){"undefined"===typeof e&&(e=!1);"undefined"===typeof c&&(c=!1);"undefined"===typeof d&&(d=!1);"undefined"===typeof b&&(b=null);"undefined"===typeof f&&(f=!1);"undefined"===typeof g&&(g=null);"undefined"===typeof m&&(m=null);this.node=a;this.childList=e;this.attributes=c;this.characterData=d;this.oldParentNode=b;this.added=f;this.attributeOldValues=g;this.characterDataOldValue=m;this.isCaseInsensitive=this.node.nodeType===Node.ELEMENT_NODE&&this.node instanceof
HTMLElement&&this.node.ownerDocument instanceof HTMLDocument}b.prototype.getAttributeOldValue=function(a){if(this.attributeOldValues)return this.isCaseInsensitive&&(a=a.toLowerCase()),this.attributeOldValues[a]};b.prototype.getAttributeNamesMutated=function(){var a=[];if(!this.attributeOldValues)return a;for(var e in this.attributeOldValues)a.push(e);return a};b.prototype.attributeMutated=function(a,e){this.attributes=!0;this.attributeOldValues=this.attributeOldValues||{};a in this.attributeOldValues||
(this.attributeOldValues[a]=e)};b.prototype.characterDataMutated=function(a){this.characterData||(this.characterData=!0,this.characterDataOldValue=a)};b.prototype.removedFromParent=function(a){this.childList=!0;this.added||this.oldParentNode?this.added=!1:this.oldParentNode=a};b.prototype.insertedIntoParent=function(){this.added=this.childList=!0};b.prototype.getOldParent=function(){if(this.childList){if(this.oldParentNode)return this.oldParentNode;if(this.added)return null}return this.node.parentNode};
return b}(),ChildListChange=function(){return function(){this.added=new NodeMap;this.removed=new NodeMap;this.maybeMoved=new NodeMap;this.oldPrevious=new NodeMap;this.moved=void 0}}(),TreeChanges=function(b){function a(a,c){b.call(this);this.rootNode=a;this.wasReachableCache=this.reachableCache=void 0;this.anyCharacterDataChanged=this.anyAttributesChanged=this.anyParentsChanged=!1;for(var d=0;d<c.length;d++){var h=c[d];switch(h.type){case "childList":this.anyParentsChanged=!0;for(var f=0;f<h.removedNodes.length;f++){var g=
h.removedNodes[f];this.getChange(g).removedFromParent(h.target)}for(f=0;f<h.addedNodes.length;f++)g=h.addedNodes[f],this.getChange(g).insertedIntoParent();break;case "attributes":this.anyAttributesChanged=!0;f=this.getChange(h.target);f.attributeMutated(h.attributeName,h.oldValue);break;case "characterData":this.anyCharacterDataChanged=!0,f=this.getChange(h.target),f.characterDataMutated(h.oldValue)}}}__extends(a,b);a.prototype.getChange=function(a){var c=this.get(a);c||(c=new NodeChange(a),this.set(a,
c));return c};a.prototype.getOldParent=function(a){var c=this.get(a);return c?c.getOldParent():a.parentNode};a.prototype.getIsReachable=function(a){if(a===this.rootNode)return!0;if(!a)return!1;this.reachableCache=this.reachableCache||new NodeMap;var c=this.reachableCache.get(a);void 0===c&&(c=this.getIsReachable(a.parentNode),this.reachableCache.set(a,c));return c};a.prototype.getWasReachable=function(a){if(a===this.rootNode)return!0;if(!a)return!1;this.wasReachableCache=this.wasReachableCache||new NodeMap;
var c=this.wasReachableCache.get(a);void 0===c&&(c=this.getWasReachable(this.getOldParent(a)),this.wasReachableCache.set(a,c));return c};a.prototype.reachabilityChange=function(a){return this.getIsReachable(a)?this.getWasReachable(a)?Movement.STAYED_IN:Movement.ENTERED:this.getWasReachable(a)?Movement.EXITED:Movement.STAYED_OUT};return a}(NodeMap),MutationProjection=function(){function b(a,e,c,d,b){this.rootNode=a;this.mutations=e;this.selectors=c;this.calcReordered=d;this.calcOldPreviousSibling=
b;this.treeChanges=new TreeChanges(a,e);this.entered=[];this.exited=[];this.stayedIn=new NodeMap;this.visited=new NodeMap;this.matchCache=this.characterDataOnly=this.childListChangeMap=void 0;this.processMutations()}b.prototype.processMutations=function(){if(this.treeChanges.anyParentsChanged||this.treeChanges.anyAttributesChanged)for(var a=this.treeChanges.keys(),e=0;e<a.length;e++)this.visitNode(a[e],void 0)};b.prototype.visitNode=function(a,e){if(!this.visited.has(a)){this.visited.set(a,!0);var c=
this.treeChanges.get(a),d=e;if(c&&c.childList||void 0==d)d=this.treeChanges.reachabilityChange(a);if(d!==Movement.STAYED_OUT){this.matchabilityChange(a);if(d===Movement.ENTERED)this.entered.push(a);else if(d===Movement.EXITED)this.exited.push(a),this.ensureHasOldPreviousSiblingIfNeeded(a);else if(d===Movement.STAYED_IN){var b=Movement.STAYED_IN;c&&c.childList&&(c.oldParentNode!==a.parentNode?(b=Movement.REPARENTED,this.ensureHasOldPreviousSiblingIfNeeded(a)):this.calcReordered&&this.wasReordered(a)&&
(b=Movement.REORDERED));this.stayedIn.set(a,b)}if(d!==Movement.STAYED_IN)for(c=a.firstChild;c;c=c.nextSibling)this.visitNode(c,d)}}};b.prototype.ensureHasOldPreviousSiblingIfNeeded=function(a){if(this.calcOldPreviousSibling){this.processChildlistChanges();var e=a.parentNode,c=this.treeChanges.get(a);c&&c.oldParentNode&&(e=c.oldParentNode);c=this.childListChangeMap.get(e);c||(c=new ChildListChange,this.childListChangeMap.set(e,c));c.oldPrevious.has(a)||c.oldPrevious.set(a,a.previousSibling)}};b.prototype.getChanged=
function(a,e,c){this.selectors=e;this.characterDataOnly=c;for(e=0;e<this.entered.length;e++){c=this.entered[e];var d=this.matchabilityChange(c);d!==Movement.ENTERED&&d!==Movement.STAYED_IN||a.added.push(c)}var b=this.stayedIn.keys();for(e=0;e<b.length;e++)c=b[e],d=this.matchabilityChange(c),d===Movement.ENTERED?a.added.push(c):d===Movement.EXITED?a.removed.push(c):d===Movement.STAYED_IN&&(a.reparented||a.reordered)&&(d=this.stayedIn.get(c),a.reparented&&d===Movement.REPARENTED?a.reparented.push(c):
a.reordered&&d===Movement.REORDERED&&a.reordered.push(c));for(e=0;e<this.exited.length;e++)c=this.exited[e],d=this.matchabilityChange(c),d!==Movement.EXITED&&d!==Movement.STAYED_IN||a.removed.push(c)};b.prototype.getOldParentNode=function(a){var e=this.treeChanges.get(a);if(e&&e.childList)return e.oldParentNode?e.oldParentNode:null;e=this.treeChanges.reachabilityChange(a);if(e===Movement.STAYED_OUT||e===Movement.ENTERED)throw Error("getOldParentNode requested on invalid node.");return a.parentNode};
b.prototype.getOldPreviousSibling=function(a){var e=a.parentNode,c=this.treeChanges.get(a);c&&c.oldParentNode&&(e=c.oldParentNode);e=this.childListChangeMap.get(e);if(!e)throw Error("getOldPreviousSibling requested on invalid node.");return e.oldPrevious.get(a)};b.prototype.getOldAttribute=function(a,e){var c=this.treeChanges.get(a);if(!c||!c.attributes)throw Error("getOldAttribute requested on invalid node.");c=c.getAttributeOldValue(e);if(void 0===c)throw Error("getOldAttribute requested for unchanged attribute name.");
return c};b.prototype.attributeChangedNodes=function(a){if(!this.treeChanges.anyAttributesChanged)return{};var e,c;if(a){e={};c={};for(var d=0;d<a.length;d++){var b=a[d];e[b]=!0;c[b.toLowerCase()]=b}}a={};for(var f=this.treeChanges.keys(),d=0;d<f.length;d++){var b=f[d],g=this.treeChanges.get(b);if(g.attributes&&Movement.STAYED_IN===this.treeChanges.reachabilityChange(b)&&Movement.STAYED_IN===this.matchabilityChange(b))for(var m=b,l=g.getAttributeNamesMutated(),n=0;n<l.length;n++)b=l[n],(!e||e[b]||
g.isCaseInsensitive&&c[b])&&g.getAttributeOldValue(b)!==m.getAttribute(b)&&(c&&g.isCaseInsensitive&&(b=c[b]),a[b]=a[b]||[],a[b].push(m))}return a};b.prototype.getOldCharacterData=function(a){a=this.treeChanges.get(a);if(!a||!a.characterData)throw Error("getOldCharacterData requested on invalid node.");return a.characterDataOldValue};b.prototype.getCharacterDataChanged=function(){if(!this.treeChanges.anyCharacterDataChanged)return[];for(var a=this.treeChanges.keys(),e=[],c=0;c<a.length;c++){var b=
a[c];if(Movement.STAYED_IN===this.treeChanges.reachabilityChange(b)){var h=this.treeChanges.get(b);h.characterData&&b.textContent!=h.characterDataOldValue&&e.push(b)}}return e};b.prototype.computeMatchabilityChange=function(a,e){this.matchCache||(this.matchCache=[]);this.matchCache[a.uid]||(this.matchCache[a.uid]=new NodeMap);var c=this.matchCache[a.uid],b=c.get(e);void 0===b&&(b=a.matchabilityChange(e,this.treeChanges.get(e)),c.set(e,b));return b};b.prototype.matchabilityChange=function(a){var e=
this;if(this.characterDataOnly)switch(a.nodeType){case Node.COMMENT_NODE:case Node.TEXT_NODE:return Movement.STAYED_IN;default:return Movement.STAYED_OUT}if(!this.selectors)return Movement.STAYED_IN;if(a.nodeType!==Node.ELEMENT_NODE)return Movement.STAYED_OUT;for(var c=this.selectors.map(function(c){return e.computeMatchabilityChange(c,a)}),b=Movement.STAYED_OUT,h=0;b!==Movement.STAYED_IN&&h<c.length;){switch(c[h]){case Movement.STAYED_IN:b=Movement.STAYED_IN;break;case Movement.ENTERED:b=b===Movement.EXITED?
Movement.STAYED_IN:Movement.ENTERED;break;case Movement.EXITED:b=b===Movement.ENTERED?Movement.STAYED_IN:Movement.EXITED}h++}return b};b.prototype.getChildlistChange=function(a){var b=this.childListChangeMap.get(a);b||(b=new ChildListChange,this.childListChangeMap.set(a,b));return b};b.prototype.processChildlistChanges=function(){if(!this.childListChangeMap){this.childListChangeMap=new NodeMap;for(var a=0;a<this.mutations.length;a++){var b=function(a,c){!a||d.oldPrevious.has(a)||d.added.has(a)||d.maybeMoved.has(a)||
c&&(d.added.has(c)||d.maybeMoved.has(c))||d.oldPrevious.set(a,c)},c=this.mutations[a];if("childList"==c.type&&(this.treeChanges.reachabilityChange(c.target)===Movement.STAYED_IN||this.calcOldPreviousSibling)){for(var d=this.getChildlistChange(c.target),h=c.previousSibling,f=0;f<c.removedNodes.length;f++){var g=c.removedNodes[f];b(g,h);d.added.has(g)?d.added["delete"](g):(d.removed.set(g,!0),d.maybeMoved["delete"](g));h=g}b(c.nextSibling,h);for(f=0;f<c.addedNodes.length;f++)g=c.addedNodes[f],d.removed.has(g)?
(d.removed["delete"](g),d.maybeMoved.set(g,!0)):d.added.set(g,!0)}}}};b.prototype.wasReordered=function(a){function b(a){if(!a||!f.maybeMoved.has(a))return!1;var d=f.moved.get(a);if(void 0!==d)return d;if(g.has(a))d=!0;else{g.set(a,!0);if(l.has(a))d=l.get(a);else{for(d=a.previousSibling;d&&(f.added.has(d)||b(d));)d=d.previousSibling;l.set(a,d)}d=d!==c(a)}g.has(a)?(g["delete"](a),f.moved.set(a,d)):d=f.moved.get(a);return d}function c(a){var d=m.get(a);if(void 0!==d)return d;for(d=f.oldPrevious.get(a);d&&
(f.removed.has(d)||b(d));)d=c(d);void 0===d&&(d=a.previousSibling);m.set(a,d);return d}if(!this.treeChanges.anyParentsChanged)return!1;this.processChildlistChanges();var d=a.parentNode,h=this.treeChanges.get(a);h&&h.oldParentNode&&(d=h.oldParentNode);var f=this.childListChangeMap.get(d);if(!f)return!1;if(f.moved)return f.moved.get(a);f.moved=new NodeMap;var g=new NodeMap,m=new NodeMap,l=new NodeMap;f.maybeMoved.keys().forEach(b);return f.moved.get(a)};return b}(),Summary=function(){function b(a,b){var c=
this;this.projection=a;this.added=[];this.removed=[];this.reparented=b.all||b.element?[]:void 0;this.reordered=b.all?[]:void 0;a.getChanged(this,b.elementFilter,b.characterData);if(b.all||b.attribute||b.attributeList){var d=a.attributeChangedNodes(b.attribute?[b.attribute]:b.attributeList);b.attribute?this.valueChanged=d[b.attribute]||[]:(this.attributeChanged=d,b.attributeList&&b.attributeList.forEach(function(a){c.attributeChanged.hasOwnProperty(a)||(c.attributeChanged[a]=[])}))}if(b.all||b.characterData)d=
a.getCharacterDataChanged(),b.characterData?this.valueChanged=d:this.characterDataChanged=d;this.reordered&&(this.getOldPreviousSibling=a.getOldPreviousSibling.bind(a))}b.prototype.getOldParentNode=function(a){return this.projection.getOldParentNode(a)};b.prototype.getOldAttribute=function(a,b){return this.projection.getOldAttribute(a,b)};b.prototype.getOldCharacterData=function(a){return this.projection.getOldCharacterData(a)};b.prototype.getOldPreviousSibling=function(a){return this.projection.getOldPreviousSibling(a)};
return b}(),validNameInitialChar=/[a-zA-Z_]+/,validNameNonInitialChar=/[a-zA-Z0-9_\-]+/;function escapeQuotes(b){return'"'+b.replace(/"/,'\\"')+'"'}
var Qualifier=function(){function b(){}b.prototype.matches=function(a){if(null===a)return!1;if(void 0===this.attrValue)return!0;if(!this.contains)return this.attrValue==a;a=a.split(" ");for(var b=0;b<a.length;b++)if(this.attrValue===a[b])return!0;return!1};b.prototype.toString=function(){return"class"===this.attrName&&this.contains?"."+this.attrValue:"id"!==this.attrName||this.contains?this.contains?"["+this.attrName+"~="+escapeQuotes(this.attrValue)+"]":"attrValue"in this?"["+this.attrName+"="+escapeQuotes(this.attrValue)+
"]":"["+this.attrName+"]":"#"+this.attrValue};return b}(),Selector=function(){function b(){this.uid=b.nextUid++;this.qualifiers=[]}Object.defineProperty(b.prototype,"caseInsensitiveTagName",{get:function(){return this.tagName.toUpperCase()},enumerable:!0,configurable:!0});Object.defineProperty(b.prototype,"selectorString",{get:function(){return this.tagName+this.qualifiers.join("")},enumerable:!0,configurable:!0});b.prototype.isMatching=function(a){return a[b.matchesSelector](this.selectorString)};
b.prototype.wasMatching=function(a,b,c){if(!b||!b.attributes)return c;var d=b.isCaseInsensitive?this.caseInsensitiveTagName:this.tagName;if("*"!==d&&d!==a.tagName)return!1;for(var d=[],h=!1,f=0;f<this.qualifiers.length;f++){var g=this.qualifiers[f],m=b.getAttributeOldValue(g.attrName);d.push(m);h=h||void 0!==m}if(!h)return c;for(f=0;f<this.qualifiers.length;f++)if(g=this.qualifiers[f],m=d[f],void 0===m&&(m=a.getAttribute(g.attrName)),!g.matches(m))return!1;return!0};b.prototype.matchabilityChange=
function(a,b){var c=this.isMatching(a);return c?this.wasMatching(a,b,c)?Movement.STAYED_IN:Movement.ENTERED:this.wasMatching(a,b,c)?Movement.EXITED:Movement.STAYED_OUT};b.parseSelectors=function(a){function e(){h&&(f&&(h.qualifiers.push(f),f=void 0),d.push(h));h=new b}function c(){f&&h.qualifiers.push(f);f=new Qualifier}for(var d=[],h,f,g=/\s/,m,l=1,n=0;n<a.length;){var k=a[n++];switch(l){case 1:if(k.match(validNameInitialChar)){e();h.tagName=k;l=2;break}if("*"==k){e();h.tagName="*";l=3;break}if("."==
k){e();c();h.tagName="*";f.attrName="class";f.contains=!0;l=4;break}if("#"==k){e();c();h.tagName="*";f.attrName="id";l=4;break}if("["==k){e();c();h.tagName="*";f.attrName="";l=6;break}if(k.match(g))break;throw Error("Invalid or unsupported selector syntax.");case 2:if(k.match(validNameNonInitialChar)){h.tagName+=k;break}if("."==k){c();f.attrName="class";f.contains=!0;l=4;break}if("#"==k){c();f.attrName="id";l=4;break}if("["==k){c();f.attrName="";l=6;break}if(k.match(g)){l=14;break}if(","==k){l=1;
break}throw Error("Invalid or unsupported selector syntax.");case 3:if("."==k){c();f.attrName="class";f.contains=!0;l=4;break}if("#"==k){c();f.attrName="id";l=4;break}if("["==k){c();f.attrName="";l=6;break}if(k.match(g)){l=14;break}if(","==k){l=1;break}throw Error("Invalid or unsupported selector syntax.");case 4:if(k.match(validNameInitialChar)){f.attrValue=k;l=5;break}throw Error("Invalid or unsupported selector syntax.");case 5:if(k.match(validNameNonInitialChar)){f.attrValue+=k;break}if("."==
k){c();f.attrName="class";f.contains=!0;l=4;break}if("#"==k){c();f.attrName="id";l=4;break}if("["==k){c();l=6;break}if(k.match(g)){l=14;break}if(","==k){l=1;break}throw Error("Invalid or unsupported selector syntax.");case 6:if(k.match(validNameInitialChar)){f.attrName=k;l=7;break}if(k.match(g))break;throw Error("Invalid or unsupported selector syntax.");case 7:if(k.match(validNameNonInitialChar)){f.attrName+=k;break}if(k.match(g)){l=8;break}if("~"==k){f.contains=!0;l=9;break}if("="==k){f.attrValue=
"";l=11;break}if("]"==k){l=3;break}throw Error("Invalid or unsupported selector syntax.");case 8:if("~"==k){f.contains=!0;l=9;break}if("="==k){f.attrValue="";l=11;break}if("]"==k){l=3;break}if(k.match(g))break;throw Error("Invalid or unsupported selector syntax.");case 9:if("="==k){f.attrValue="";l=11;break}throw Error("Invalid or unsupported selector syntax.");case 10:if("]"==k){l=3;break}if(k.match(g))break;throw Error("Invalid or unsupported selector syntax.");case 11:if(k.match(g))break;if('"'==
k||"'"==k){m=k;l=13;break}f.attrValue+=k;l=12;break;case 12:if(k.match(g)){l=10;break}if("]"==k){l=3;break}if("'"==k||'"'==k)throw Error("Invalid or unsupported selector syntax.");f.attrValue+=k;break;case 13:if(k==m){l=10;break}f.attrValue+=k;break;case 14:if(k.match(g))break;if(","==k){l=1;break}throw Error("Invalid or unsupported selector syntax.");}}switch(l){case 1:case 2:case 3:case 5:case 14:e();break;default:throw Error("Invalid or unsupported selector syntax.");}if(!d.length)throw Error("Invalid or unsupported selector syntax.");
return d};b.nextUid=1;b.matchesSelector=function(){var a=document.createElement("div");return"function"===typeof a.webkitMatchesSelector?"webkitMatchesSelector":"function"===typeof a.mozMatchesSelector?"mozMatchesSelector":"function"===typeof a.msMatchesSelector?"msMatchesSelector":"matchesSelector"}();return b}(),attributeFilterPattern=/^([a-zA-Z:_]+[a-zA-Z0-9_\-:\.]*)$/;
function validateAttribute(b){if("string"!=typeof b)throw Error("Invalid request opion. attribute must be a non-zero length string.");b=b.trim();if(!b)throw Error("Invalid request opion. attribute must be a non-zero length string.");if(!b.match(attributeFilterPattern))throw Error("Invalid request option. invalid attribute name: "+b);return b}
function validateElementAttributes(b){if(!b.trim().length)throw Error("Invalid request option: elementAttributes must contain at least one attribute.");var a={},e={};b=b.split(/\s+/);for(var c=0;c<b.length;c++){var d=b[c];if(d){var d=validateAttribute(d),h=d.toLowerCase();if(a[h])throw Error("Invalid request option: observing multiple case variations of the same attribute is not supported.");e[d]=!0;a[h]=!0}}return Object.keys(e)}
function elementFilterAttributes(b){var a={};b.forEach(function(b){b.qualifiers.forEach(function(b){a[b.attrName]=!0})});return Object.keys(a)}
var MutationSummary=function(){function b(a){var e=this;this.connected=!1;this.options=b.validateOptions(a);this.observerOptions=b.createObserverOptions(this.options.queries);this.root=this.options.rootNode;this.callback=this.options.callback;this.elementFilter=Array.prototype.concat.apply([],this.options.queries.map(function(a){return a.elementFilter?a.elementFilter:[]}));this.elementFilter.length||(this.elementFilter=void 0);this.calcReordered=this.options.queries.some(function(a){return a.all});
this.queryValidators=[];b.createQueryValidator&&(this.queryValidators=this.options.queries.map(function(a){return b.createQueryValidator(e.root,a)}));this.observer=new MutationObserverCtor(function(a){e.observerCallback(a)});this.reconnect()}b.createObserverOptions=function(a){function b(a){if(!c.attributes||d)c.attributes=!0,c.attributeOldValue=!0,a?(d=d||{},a.forEach(function(a){d[a]=!0;d[a.toLowerCase()]=!0})):d=void 0}var c={childList:!0,subtree:!0},d;a.forEach(function(a){a.characterData?(c.characterData=
!0,c.characterDataOldValue=!0):a.all?(b(),c.characterData=!0,c.characterDataOldValue=!0):a.attribute?b([a.attribute.trim()]):(a=elementFilterAttributes(a.elementFilter).concat(a.attributeList||[]),a.length&&b(a))});d&&(c.attributeFilter=Object.keys(d));return c};b.validateOptions=function(a){for(var e in a)if(!(e in b.optionKeys))throw Error("Invalid option: "+e);if("function"!==typeof a.callback)throw Error("Invalid options: callback is required and must be a function");if(!a.queries||!a.queries.length)throw Error("Invalid options: queries must contain at least one query request object.");
e={callback:a.callback,rootNode:a.rootNode||document,observeOwnChanges:!!a.observeOwnChanges,oldPreviousSibling:!!a.oldPreviousSibling,queries:[]};for(var c=0;c<a.queries.length;c++){var d=a.queries[c];if(d.all){if(1<Object.keys(d).length)throw Error("Invalid request option. all has no options.");e.queries.push({all:!0})}else if("attribute"in d){var h={attribute:validateAttribute(d.attribute)};h.elementFilter=Selector.parseSelectors("*["+h.attribute+"]");if(1<Object.keys(d).length)throw Error("Invalid request option. attribute has no options.");
e.queries.push(h)}else if("element"in d){var f=Object.keys(d).length,h={element:d.element,elementFilter:Selector.parseSelectors(d.element)};d.hasOwnProperty("elementAttributes")&&(h.attributeList=validateElementAttributes(d.elementAttributes),f--);if(1<f)throw Error("Invalid request option. element only allows elementAttributes option.");e.queries.push(h)}else if(d.characterData){if(1<Object.keys(d).length)throw Error("Invalid request option. characterData has no options.");e.queries.push({characterData:!0})}else throw Error("Invalid request option. Unknown query request.");
}return e};b.prototype.createSummaries=function(a){if(!a||!a.length)return[];a=new MutationProjection(this.root,a,this.elementFilter,this.calcReordered,this.options.oldPreviousSibling);for(var b=[],c=0;c<this.options.queries.length;c++)b.push(new Summary(a,this.options.queries[c]));return b};b.prototype.checkpointQueryValidators=function(){this.queryValidators.forEach(function(a){a&&a.recordPreviousState()})};b.prototype.runQueryValidators=function(a){this.queryValidators.forEach(function(b,c){b&&
b.validate(a[c])})};b.prototype.changesToReport=function(a){return a.some(function(a){return"added removed reordered reparented valueChanged characterDataChanged".split(" ").some(function(b){return a[b]&&a[b].length})||a.attributeChanged&&Object.keys(a.attributeChanged).some(function(b){return!!a.attributeChanged[b].length})?!0:!1})};b.prototype.observerCallback=function(a){this.options.observeOwnChanges||this.observer.disconnect();a=this.createSummaries(a);this.runQueryValidators(a);this.options.observeOwnChanges&&
this.checkpointQueryValidators();this.changesToReport(a)&&this.callback(a);!this.options.observeOwnChanges&&this.connected&&(this.checkpointQueryValidators(),this.observer.observe(this.root,this.observerOptions))};b.prototype.reconnect=function(){if(this.connected)throw Error("Already connected");this.observer.observe(this.root,this.observerOptions);this.connected=!0;this.checkpointQueryValidators()};b.prototype.takeSummaries=function(){if(!this.connected)throw Error("Not connected");var a=this.createSummaries(this.observer.takeRecords());
return this.changesToReport(a)?a:void 0};b.prototype.disconnect=function(){var a=this.takeSummaries();this.observer.disconnect();this.connected=!1;return a};b.NodeMap=NodeMap;b.parseElementFilter=Selector.parseSelectors;b.optionKeys={callback:!0,queries:!0,rootNode:!0,oldPreviousSibling:!0,observeOwnChanges:!0};return b}(),SummaryResult=function(b){this.rootNode=b;this.result={countElementsWithVisibilityChange:-1,fieldsWithNewOptions:[],newEnabledFields:[],newDisabledFields:[],appearedEnabledFields:[],
appearedDisabledFields:[],enabledFields:[],disabledFields:[],textVaried:[],fieldsWithRemovedOptions:[],removedFields:[],disappearedFields:[],fieldsWithCSSChange:[]};this.reportNewText=function(a){this.result.textVaried.push(a)};this.reportFieldWithRemovedOption=function(a){this.result.fieldsWithRemovedOptions.push(toJava(a))};this.reportRemovedField=function(a){this.result.removedFields.push(toJava(a))};this.reportDisappearedField=function(a){this.result.disappearedFields.push(toJava(a))};this.reportDisabledField=
function(a){this.result.disabledFields.push(toJava(a))};this.reportEnabledField=function(a){this.result.enabledFields.push(toJava(a))};this.reportNewField=function(a,b){b?this.result.newEnabledFields.push(toJava(a)):this.result.newDisabledFields.push(toJava(a))};this.reportAppearedField=function(a,b){b?this.result.appearedEnabledFields.push(toJava(a)):this.result.appearedDisabledFields.push(toJava(a))};this.reportFieldWithAddedOption=function(a){this.result.fieldsWithNewOptions.push(toJava(a))};this.reportFieldWithCSSChange=
function(a){this.result.fieldsWithCSSChange.push(toJava(a))};this.analyseMutationSummary=function(a,b){for(var c=[],d=[],h=[],f=0;f<a.length;f++)var g=a[f],d=d.concat(g.removed),c=c.concat(g.added),h=h.concat(g.characterDataChanged);var d=d.filter(function(a,b){var d=a.nodeType===Node.TEXT_NODE;if(d&&(0===a.textContent.length||WebUtils.isWhiteSpace(a.data)))return!1;var e=hadLocator(d?a.parentNode:a);if(!e)return!0;e=getNodeByXPath(e,document);if(!e)return!0;if(d){for(var f=a.data,h=0;h<c.length;h++){var g=
c[h];if(g&&(d=g.nodeType===Node.TEXT_NODE)&&g.parentNode===e&&g.data===f)return}return!0}d=c.indexOf(e);if(-1==d)return!0;c[d]=null;return!1},this),c=c.filter(function(a){return null!==a}),f=[],g=[],m=[],l=getNodesByXPath("descendant-or-self::*",this.rootNode),f=f.concat(this.visitRemovedElements(d)),f=f.concat(this.findDisappearedField(l,f)),g=g.concat(this.visitAddedElements(c,f)),g=g.concat(this.findAppearedField(l,g,f));this.findFieldEnabledDisabled(l,g,f);this.reportFieldWithOptions(c,g,f,function(a){this.reportFieldWithAddedOption(a)});
d=h.concat(c);m=m.concat(this.visitAddedTextNodes(d,g,f));this.findAppearedText(l,m);d=this.countThoseElementsWithVisibilityChange(l);this.result.countElementsWithVisibilityChange=d;this.findFieldsWithCSSChanges(l,b,g,f);return this.result};this.countThoseElementsWithVisibilityChange=function(a){var b=0;a.forEach(function(a){!a||!a.nodeName||WebUtils.isFieldTag(a.nodeName)||WebUtils.isOptionNode(a)||"IMG"!==a.nodeName&&(0===a.textContent.length||WebUtils.isWhiteSpace(a.textContent))||(wasInitiallyShown(a)===
DISPLAYED.FALSE&&isShownNow(a)&&b++,wasInitiallyShown(a)!==DISPLAYED.TRUE||isShownNow(a)||b++)},this);return b};this.findAppearedField=function(a,b,c){var d=[];a.forEach(function(a){WebUtils.isFieldTag(a.nodeName)&&!WebUtils.arrayContains(c,a)&&!WebUtils.arrayContains(b,a)&&wasInitiallyShown(a)===DISPLAYED.FALSE&&isShownNow(a)&&(this.reportAppearedField(a,isEnabledNow(a)),d.push(a))},this);return d};this.findDisappearedField=function(a,b){var c=[];a.forEach(function(a){!WebUtils.isFieldTag(a.nodeName)||
WebUtils.arrayContains(b,a)||wasInitiallyShown(a)!==DISPLAYED.TRUE||isShownNow(a)||(c.push(a),this.reportDisappearedField(a))},this);return c};this.findAppearedText=function(a,b){var c=[];a.forEach(function(a){!a.parentNode||WebUtils.isFieldTag(a.nodeName)||WebUtils.isOptionNode(a)||wasInitiallyShown(a)!==DISPLAYED.FALSE||0===a.textContent.length||WebUtils.isWhiteSpace(a.textContent)||!isShownNow(a)||(a=bot_dom_getVisibleText(a),WebUtils.arrayContains(c,a)||WebUtils.arrayContains(b,a)||(c.push(a),
this.reportNewText(a)))},this)};this.visitAddedTextNodes=function(a,b,c){var d=[];a.forEach(function(a){a.nodeType===Node.TEXT_NODE&&a.parentNode&&!WebUtils.isOptionNode(a.parentNode)&&0!==a.textContent.length&&!WebUtils.isWhiteSpace(a.textContent)&&isShownNow(a.parentNode)&&(a=a.textContent,WebUtils.arrayContains(d,a)||(d.push(a),this.reportNewText(a)))},this);return d};this.visitAddedElements=function(a,b){var c=[];a.forEach(function(a){if(a.nodeType===Node.ELEMENT_NODE&&WebUtils.isFieldTag(a.nodeName)){var h;
h=WebUtils.arrayContains(c,a)?!1:WebUtils.arrayContains(b,a)?!1:isShownNow(a);h&&(c.push(a),this.reportNewField(a,isEnabledNow(a)))}},this);return c};this.findFieldsWithCSSChanges=function(a,b,c,d){var h=[];a.forEach(function(a){if(wasInitiallyShown(a)===DISPLAYED.TRUE&&WebUtils.isFieldTag(a.nodeName)&&!WebUtils.arrayContains(d,a)&&!WebUtils.arrayContains(c,a)&&!WebUtils.arrayContains(h,a)&&isShownNow(a)){var g=a[WebUtils.diademNS];if(g)for(var m=0;m<b.length;m++){var l=b[m];if(g[l]!==getCssPropertyValue(a,
l)){this.reportFieldWithCSSChange(a);break}}}},this)};this.findFieldEnabledDisabled=function(a,b,c){a.forEach(function(a){!WebUtils.isFieldTag(a.nodeName)||WebUtils.arrayContains(c,a)||WebUtils.arrayContains(b,a)||(wasInitiallyEnabled(a)!==DISPLAYED.TRUE||isEnabledNow(a)||this.reportDisabledField(a),wasInitiallyEnabled(a)===DISPLAYED.FALSE&&isEnabledNow(a)&&this.reportEnabledField(a))},this)};this.reportFieldWithOptions=function(a,b,c,d){var h=[];a.forEach(function(a){if(WebUtils.isOptionNode(a)){a=
WebUtils.findFieldOfOption(a);var g;if(g=a)g=WebUtils.arrayContains(h,a)||WebUtils.arrayContains(c,a)||WebUtils.arrayContains(b,a)?!1:wasInitiallyShown(a)===DISPLAYED.TRUE;g&&(d.call(this,a),h.push(a))}},this)};this.visitRemovedElements=function(a){var b=[];a.forEach(function(a){a.nodeType===Node.ELEMENT_NODE&&wasInitiallyShown(a)===DISPLAYED.TRUE&&WebUtils.isFieldTag(a.nodeName)&&!WebUtils.arrayContains(b,a)&&(this.reportRemovedField(a),b.push(a))},this);return b}},DISPLAYED={TRUE:!0,FALSE:!1,DONTKNOW:"dontknow"};
function isEnabledNow(b){return bot_dom_isEnabled(b)}function isShownNow(b){return bot_dom_isShown(b)?DISPLAYED.TRUE:DISPLAYED.FALSE}function wasInitiallyShown(b){return(b=b[WebUtils.diademNS])?"wasInitiallyShown"in b?b.wasInitiallyShown?DISPLAYED.TRUE:DISPLAYED.FALSE:DISPLAYED.DONTKNOW:DISPLAYED.DONTKNOW}function wasInitiallyEnabled(b){return(b=b[WebUtils.diademNS])?"wasInitiallyEnabled"in b?b.wasInitiallyEnabled?DISPLAYED.TRUE:DISPLAYED.FALSE:DISPLAYED.DONTKNOW:DISPLAYED.DONTKNOW}
function hadLocator(b){return b?(b=b[WebUtils.diademNS])?"locator"in b?b.locator:null:null:null}function observeStyle(b,a){getNodesByXPath("descendant-or-self::*",b).forEach(function(b){if(b&&!WebUtils.isOptionNode(b)){var c={};c.wasInitiallyShown=isShownNow(b);c.wasInitiallyEnabled=isEnabledNow(b);c.locator=_getXPathLocator(b);if(WebUtils.isFieldTag(b.nodeName))for(var d=0;d<a.length;d++){var h=a[d];c[h]=getCssPropertyValue(b,h)}b[WebUtils.diademNS]=c}},this)}
function createVisibilityObserver(b,a,e){}
function createSummaryObserver(b,a,e){"undefined"===typeof window.observerArray&&(window.observerArray=[]);"undefined"===typeof window.observerArray[b]&&(window.observerArray[b]=[]);var c=new MutationSummary({callback:function(a){"undefined"===typeof window.mutation_summary&&(window.mutation_summary={});"undefined"===typeof window.mutation_summary[b]&&(window.mutation_summary[b]=[]);a.forEach(function(a){window.mutation_summary[b].push(a)})},rootNode:a,queries:[{all:!0}]});window.observerArray[b]=
c;observeStyle(a,e);return c}function disconnectSummaryObserver(b){if(!window.observerArray||!window.observerArray[b])return console.log("no observer for "+b),null;var a=window.observerArray[b],e=a.disconnect();e&&a.callback(e);window.observerArray[b]=null;return a.root}
function takeMutationSummary(b,a,e){var c=disconnectSummaryObserver(b);a=new SummaryResult(c);if(!c)return a.result;if(!window.mutation_summary||!window.mutation_summary[b])return console.log("no mutations for "+b),a.analyseMutationSummary([],e);c=window.mutation_summary[b];window.mutation_summary[b]=null;return a.analyseMutationSummary(c,e)};